services:
  - type: web
    plan: free
    name: Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/mlmirror/MOONLIGHT-RENAME-BOT
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: ADMIN
        sync: false
